ci: align image name and cloud run service

diff --git a/.github/workflows/main-ci-cd.yml b/.github/workflows/main-ci-cd.yml
--- a/.github/workflows/main-ci-cd.yml
+++ b/.github/workflows/main-ci-cd.yml
@@ -44,26 +44,27 @@ jobs:
         uses: actions/checkout@v3
       - name: 'Validate Secrets and Variables'
         run: |
-          if [ -z "${{ secrets.GCP_SA_KEY || '' }}" ]; then echo "::error::GCP_SA_KEY secret is NOT set." && exit 1; fi
-          if [ -z "${{ vars.GCP_PROJECT_ID || '' }}" ]; then echo "::error::GCP_PROJECT_ID var is NOT set." && exit 1; fi
-          if [ -z "${{ vars.GCP_REGION || '' }}" ]; then echo "::error::GCP_REGION var is NOT set." && exit 1; fi
-          if [ -z "${{ vars.GAR_REPOSITORY || '' }}" ]; then echo "::error::GAR_REPOSITORY var is NOT set." && exit 1; fi
-          if [ -z "${{ vars.CLOUD_RUN_SERVICE || '' }}" ]; then echo "::error::CLOUD_RUN_SERVICE var is NOT set." && exit 1; fi
+          if [ -z "${{ secrets.GCP_SA_KEY || '' }}" ]; then echo "::error::Secret GCP_SA_KEY is not set." && exit 1; fi
+          if [ -z "${{ vars.GCP_PROJECT_ID || '' }}" ]; then echo "::error::Variable GCP_PROJECT_ID is not set." && exit 1; fi
+          if [ -z "${{ vars.GCP_REGION || '' }}" ]; then echo "::error::Variable GCP_REGION is not set." && exit 1; fi
+          if [ -z "${{ vars.GAR_REPOSITORY || '' }}" ]; then echo "::error::Variable GAR_REPOSITORY is not set." && exit 1; fi
+          if [ -z "${{ vars.DOCKER_IMAGE_NAME || '' }}" ]; then echo "::error::Variable DOCKER_IMAGE_NAME (source for build) is not set." && exit 1; fi
+          if [ -z "${{ vars.CLOUD_RUN_SERVICE || '' }}" ]; then echo "::error::Variable CLOUD_RUN_SERVICE (target for deploy) is not set." && exit 1; fi
       - name: Authenticate to Google Cloud
         uses: 'google-github-actions/auth@v2'
         with:
           credentials_json: '${{ secrets.GCP_SA_KEY }}'
       - name: Configure Docker
         run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet
-      
       - name: Build, Push, and Deploy
         env:
           GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
           GCP_REGION: ${{ vars.GCP_REGION }}
           GAR_REPOSITORY: ${{ vars.GAR_REPOSITORY }}
-          SERVICE_NAME: ${{ vars.CLOUD_RUN_SERVICE }}
+          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
+          CLOUD_RUN_SERVICE: ${{ vars.CLOUD_RUN_SERVICE }}
           IMAGE_TAG: ${{ github.sha }}
           GCP_RUN_SERVICE_ACCOUNT: ${{ vars.GCP_RUN_SERVICE_ACCOUNT || '' }}
         run: |
-          chmod +x ./scripts/build_and_deploy_service.sh
-          ./scripts/build_and_deploy_service.sh
+          chmod +x ./scripts/build-and-deploy.sh
+          ./scripts/build-and-deploy.sh
