ci: add debug step to check for GCP_SA_KEY presence

diff --git a/.github/workflows/main-ci-cd.yml b/.github/workflows/main-ci-cd.yml
--- a/.github/workflows/main-ci-cd.yml
+++ b/.github/workflows/main-ci-cd.yml
@@ -46,6 +46,15 @@ jobs:
 
       - name: Set up Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v1
+
+      - name: 'Debug: Check GCP_SA_KEY presence'
+        run: |
+          if [ "${{ secrets.GCP_SA_KEY == '' }}" == "true" ]; then
+            echo "GCP_SA_KEY secret is NOT set. Failing."
+            exit 1
+          else
+            echo "GCP_SA_KEY secret is SET."
+          fi
       
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v1
@@ -77,6 +86,15 @@ jobs:
 
       - name: Set up Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v1
+
+      - name: 'Debug: Check GCP_SA_KEY presence'
+        run: |
+          if [ "${{ secrets.GCP_SA_KEY == '' }}" == "true" ]; then
+            echo "GCP_SA_KEY secret is NOT set. Failing."
+            exit 1
+          else
+            echo "GCP_SA_KEY secret is SET."
+          fi
 
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v1
